### ISSUE TITLE
Doesn't work on OSX/MacOS

### ISSUE THREAD

**Issue by bertBruynooghe** [barkerest/hidapi#3]
As pointed out in several threads online, you can't access HID through libusb.lib on Mac, so this one doesn't work either. 

(a.o.: (https://github.com/tessel/node-usb/issues/30#issuecomment-244477201))

I'm not expecting you to fix this; just leaving this note for others experiencing the same...

**Comment by barkerest** [comment]
I haven't tried it in 10.12 yet, but it certainly worked in 10.11 fine with the kext generated by HIDAPI::SetupTaskHelper.  The kext is supposed to disconnect the specific HID device from the kernel's HID driver, thereby allowing libusb to access the device.  Did you receive a specific error when you attempted using the library?

**Comment by bertBruynooghe** [comment]
You're absolutely right, I didn't notice the kext section in the readme while hurrying to get something working. Sorry :(
