### ISSUE TITLE
HIDAPI::SetupTaskHelper.stop

### ISSUE THREAD

**Issue by jhgorse** [barkerest/hidapi#8]
Shouldn't we have a way to remove this kext easily? Such as
HIDAPI::SetupTaskHelper.stop

By the way, IRB is kind of limited. It does not show that .run is a method of HIDAPI::SetupTaskHelper. Wouldn't it be nice to see methods and data members of objects... anyway, that is enough for today.

**Comment by barkerest** [comment]
SetupTaskHelper is a setup program.  It's not something that runs in the background to stop.  But adding an uninstall routine could be useful.  I would encourage a pull request if you wanted to add that feature.

**Comment by jhgorse** [comment]
okay. https://github.com/barkerest/hidapi/pull/9
